remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Victor Leny
description: Ingénieur, responsable de la modélisation du plan climat pour la France Empreinte2050.
show_downloads: false
